version: '3.9'

services:
  built-nginx:
    build:
      context: .
      dockerfile: deploy-helper/nginx/Dockerfile.nginx
    ports:
      - 8080:80
    depends_on:
      - php-fpm

    environment:
      - NGINX_HOST=server-web
      - NGINX_PORT=80

  php-fpm:
    container_name: server-web
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /var/www/

    depends_on:
      - test-db

    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=test-db
      - DB_PORT=3306
      - DB_DATABASE=test-db
      - DB_USERNAME=root
      - DB_PASSWORD=12345678

  test-db:
    image: mariadb
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    # volumes: 
    #   - ~/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 12345678
      # MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - 3306:3306
      - 33060:33060
